linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled due to personal preference
    - depguard
    - exhaustruct
    - gomnd
    - nlreturn
    - tagliatelle
    - unparam
    - wrapcheck
    - wsl
    # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    # TODO reevaluate
    - containedctx
    - gocritic
    - goerr113
    - inamedparam
    - musttag
    - nestif
    - nonamedreturns
    - prealloc
    - varnamelen

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sapslaj/eks-pricing-exporter)
      - blank
      - dot
    custom-order: true

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
    - indent-error-flow # revive
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - exhaustive
        - forcetypeassert
        - funlen
        - paralleltest # TODO
        - goconst # TODO
    - path: zz_generated
      linters:
        - gochecknoglobals
        - gofumpt
        - gofmt
        - goimports
        - unused
