{
 "title": "EKS Node Viewer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodes",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "nodes" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum)",
     "legendFormat": "req"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Cluster Resource Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Cost Per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(eks_node_hourly_price)", "legendFormat": "hourly" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum)",
     "legendFormat": "req"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Cost Per Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eks_node_hourly_price) * 730",
     "legendFormat": "hourly"
    }
   ]
  },
  { "title": "$nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "nodes" },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "eks_node_info{node=~\"$nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase * on(pod) group_left(node) kube_pod_info{node=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resource Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$nodes\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$nodes\"})",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$nodes\"}) / sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$nodes\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Cost Per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eks_node_hourly_price{node=~\"$nodes\"})",
     "legendFormat": "hourly"
    }
   ]
  },
  {
   "title": "Cost Per Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eks_node_hourly_price{node=~\"$nodes\"}) * 730",
     "legendFormat": "hourly"
    }
   ]
  }
 ]
}